version: 2

sources:
  - name: jaffle_shop
    description: This is a replica of the Postgres database used by our app
    database: raw
    schema: jaffle_shop
    tables:
      - name: customers
        description: One record per customer.
        columns:
          - name: id
            tests:
              - not_null
      - name: orders
        description: One record per order. Includes cancelled and deleted orders.
        columns:
          - name: status
            description: '{{ doc("order_status")}}'
